config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :challenges do
    resources :participations, only: [:create]
  end
  resources :users, only: [:show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/challenge.rb
class Challenge < ApplicationRecord
  attr_accessor :str_date

  belongs_to :user
  has_many :participations, dependent: :destroy
  has_many :users, through: :participations
  validates :date, presence: true

  # validates :title, :place, :date, presence: true

  enum status: { ongoing: 0, finished: 1 }

  mount_uploader :photo, PhotoUploader
  mount_uploader :photo_after, PhotoUploader

  validates :photo, presence: true
  # validates :photo_after, presence: true

  geocoded_by :place
  after_validation :geocode

  def format_date
    date.strftime(" %A %e %B %Y - %l:%M")
  end
end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :user
  belongs_to :challenge
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :challenges
  has_many :participations
  has_many :participated_challenges, through: :participations, source: :challenge
  # validates :first_name, :last_name, presence: true

  def score_to_percentage
    maxed_score = [score, 1000].min
    (maxed_score * 100) / 1000
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def default_url_options
  { host: ENV["www.trashtag.pro"] || "localhost:3000" }
  end

end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @challenges = Challenge.where.not(latitude: nil, longitude: nil)

    @markers = @challenges.map do |challenge|
      {
        lat: challenge.latitude,
        lng: challenge.longitude,
        image_url: helpers.asset_url('garbage.png')
      }
    end
  end

  def show
    @challenge = Challenge.find(params[:id])
  end

  def new
    @challenge = Challenge.new
  end

  def create
    @challenge = Challenge.new(challenge_params)
    @user = current_user
    @challenge.user = @user
    if @challenge.save
      redirect_to challenge_path(@challenge)
    else
      render 'new'
    end
  end

  def edit
    @challenge = Challenge.find(params[:id])
  end

  def update
    @challenge = Challenge.find(params[:id])

    if @challenge.update(challenge_params.merge(status: 1))
      organizer = @challenge.user
      organizer.score += 20
      organizer.save
      @challenge.users.each do |participant|
        participant.score += 10
        participant.save
      end

      redirect_to challenge_path(@challenge)
    else
      render 'update'
    end
  end

  def destroy
    @challenge = Challenge.find(params[:id])
    @challenge.destroy
    redirect_to challenges_path
  end

  private

  def challenge_params
    parameters = params.require(:challenge).permit(:title, :place, :str_date, :photo, :photo_after)
    parameters.merge!({ date: DateTime.parse(params[:challenge][:str_date]) }) if params[:challenge][:str_date].present?
    # parameters[:date] = DateTime.parse(params[:challenge][:str_date])
    return parameters
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController

    def create
        @user = current_user
        @challenge = Challenge.find(params[:challenge_id])
        @participation = Participation.new
        @participation.challenge = @challenge
        @participation.user = @user
        if @participation.save
            redirect_to challenges_path(@challenge)
        else
            render :new
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    if params[:id]
      @user = User.find(params[:id])
    else
      @user = current_user
    end
  end

  def index
    @users = User.all
    @top_users = @users.sort_by {|user| user.score }.last(3).reverse
    @last_users = @users.sort_by {|user| user.score }.first(4).reverse
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/score_helper.rb
module ScoreHelper
  def user_score_to_css_width(user)
    "width: #{user.score_to_percentage}%;"
  end

  def user_score_to_css_position(user)
    "left: calc(#{user.score_to_percentage}% - 25px);"
  end
end

app/views/challenges/edit.html.erb
<div class="challenge_edit">
  <div class="edit">
    <div class="card">
      <h3 class="text-center">Enclose your challenge</h3>

      <%= simple_form_for @challenge do |f| %>
        <%= f.input :photo_after, label: "Add your ending photo" %>
        <%= f.input :photo_cache, as: :hidden %>
        <div class="text-center">
          <%= f.submit 'Enclose challenge', class: 'submit btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/challenges/index.html.erb
<div class="challenges-index">

  <%= simple_form_for :search, url: challenges_path, method: :get do |f| %>
    <div class="search-form-control form-group">
      <input class="form-control string required" type="text" name="search[query]" id="search_query" placeholder="Let's challenge yourself !" />
      <button name="button" type="submit" class="btn btn-primary">
        <i class="fas fa-search"></i> Search
      </button>
    </div>
  <% end %>

  <div>
    <div
    id="map"
    style="width: 100%;
    height: 35vh;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
    ></div>
  </div>

  <div class="last-challenges-list">
    <div class="cards-challenges-list cards-margin-4">
      <% @challenges.each do |challenge| %>

        <div class="card-challenge">
          <%= cl_image_tag challenge.photo, height: 100, width: 150, crop: :fill %>
          <div class="card-challenge-infos-16">
            <h6><%= challenge.title %></h6>
            <p><%= challenge.place %></p>
            <p><%= challenge.format_date %></p>
            <%= link_to "More details", challenge_path(challenge), class: 'btn btn-primary' %>
          </div>
        </div>

      <% end %>
    </div>
  </div>

</div>

app/views/challenges/new.html.erb
<div class="container new-challenge-form">
  <div class="challenge-new">
    <div class="card">
      <h3 class="text-center">Create your challenge</h3>
      <div class="container container-without-height">
        <%= simple_form_for @challenge do |f| %>
            <%= f.input :title, placeholder: "Enter challenge title" %>
            <%= f.input :place, placeholder: "Enter challenge address" %>
            <%= f.input :photo %>
            <%= f.input :photo_cache, as: :hidden %>
            <div class="input-append date form_datetime">
              <%= f.input :str_date, label: "Date du challenge" , as: :string, input_html: {class: "datepicker"} %>
              <span class="add-on"><i class="icon-th"></i></span>
              </div>
              <div class="text-center">
                <%= f.submit class: 'submit btn btn-primary btn-cta' %>
              </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/challenges/show.html.erb
<div class="challenge-details">
  <%= cl_image_tag @challenge.photo, height: 300, width: 300, crop: :fill %>

  <div id="challenge-organizer">
    <%= cl_image_tag @challenge.user.photo, class: "challenge-details-user avatar-bordered mx-auto d-block" %>
  </div>
</div>

<div class="container texts-infos d-flex justify-content-around mt-5 text-center">

  <h2><%= @challenge.title %></h2>
  <!-- fa-globe-americas -->
  <p><i class="fas fa-map-marker-alt"></i> <%= @challenge.place %></p>
  <p><i class="far fa-calendar-check"></i> <%= @challenge.format_date %></p>
  <div class="challenge-details-participations">
    <h1><i class="fas fa-users"></i> <%= @challenge.participations.count %></h1>
    <h5>participants</h5>
  </div>

  <div class="buttons-infos d-flex justify-content-around">
    <div class="text-center">
      <% if current_user == @challenge.user && @challenge.ongoing? %>
        <%= link_to edit_challenge_path(@challenge), class: 'btn btn-success btn-cta' do %>
          <i class="fas fa-check-circle"></i> Enclose
        <% end %>
      <% elsif @challenge.ongoing? %>
        <%= link_to "Participate", challenge_participations_path(@challenge), class: 'btn btn-success btn-cta', method: :post %>
      <% else %>
        <p>This is a past challenge.</p>
        <%= cl_image_tag @challenge.photo_after, height: 300, width: 300, crop: :fill, class: 'photo-challenge-after'  %>
      <% end %>
    </div>
  </div>
  <div id="share-buttons">
    <!-- Facebook --> <a href="https://www.facebook.com/sharer.php?u=https://www.trashtag.pro/challenges/<% @challenge.id %>" target="_blank"><img src="https://4.bp.blogspot.com/-raFYZvIFUV0/UwNI2ek6i3I/AAAAAAAAGSA/zs-kwq0q58E/s1600/facebook.png" alt="Facebook" /></a> <!-- Twitter --> <a href="https://twitter.com/share?url=https://www.trashtag.pro/challenges/<% @challenge.id %>&text=Simple Share Buttons" target="_blank"><img src="https://4.bp.blogspot.com/--ISQEurz3aE/UwNI4hDaQMI/AAAAAAAAGS4/ZAgmPiM9Xpk/s1600/twitter.png" alt="Twitter" /></a> <!-- LinkedIn --> <a href="https://www.linkedin.com/shareArticle?mini=true&url=https://www.trashtag.pro/challenges/<% @challenge.id %>" target="_blank"><img src="https://2.bp.blogspot.com/-3_cATk7Wlho/UwNI3eoTTLI/AAAAAAAAGSQ/Y8cpq6S-SeQ/s1600/linkedin.png" alt="LinkedIn" /></a> <!-- Pinterest --> <a href="javascript:void((function()%7Bvar%20e=document.createElement('script');e.setAttribute('type','text/javascript');e.setAttribute('charset','UTF-8');e.setAttribute('src','https://assets.pinterest.com/js/pinmarklet.js?r='+Math.random()*99999999);document.body.appendChild(e)%7D)());"><img src="https://2.bp.blogspot.com/-3CfsOmDx-Dg/UwNI3kMVjgI/AAAAAAAAGSU/OSixn3lcjX4/s1600/pinterest.png" alt="Pinterest" /></a> <!-- Email --> <a href="mailto:?Subject=FrinMash&Body=I%20saw%20this%20and%20thought%20of%20you!%20 https://www.trashtag.pro/challenges/<% @challenge.id %>"><img src="https://4.bp.blogspot.com/-njgKtNLrPqI/UwNI2o-9WfI/AAAAAAAAGR4/f8da1gBgyLs/s1600/email.png" alt="Email" /></a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, maximum-scale=1, user-scalable=no, minimal-ui">
    <link href="https://fonts.googleapis.com/css?family=Libre+Baskerville:400,400i,700&display=swap" rel="stylesheet">
    <%= favicon_link_tag 'favicon.ico' %>

    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">


    <title>Trashtag</title>

    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/navbar' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
  <div class="container">
    <h1>Trashtag</h1>
    <div class="text-center banner-content">
      <h2>It's time to save the earth, more than ever</h2>
      <div class="arrow bounce">
        <div class="fa fa-arrow-down fa-2x"></div>
      </div>
      <%= link_to "Create your challenge", new_challenge_path, class: 'btn btn-success btn-lg btn-cta' %>
    </div>
    <div id="link-home">
      <%= link_to "Or see challenges list", challenges_path %>
    </div>
  </div>
</div>

app/views/participations/index.html.erb
<h1>participation#index</h1>
<p>Find me in app/views/participations/index.html.erb</p>

app/views/shared/_navbar.html.erb
<div class="navbar fixed-bottom navbar-expand-sm navbar-light navbar-lewagon">
  <ul class="navbar-nav w-100 d-flex flex-row justify-content-around" >
    <% if user_signed_in? %>

      <li class="nav-item">
        <%= link_to root_path, class: "nav-link" do %>
          <% if current_page?(root_path) %>
            <i class="fas fa-home active" ></i>
          <% else %>
            <i class="fas fa-home" ></i>
          <% end %>
        <% end %>
      </li>

      <li class="nav-item">
      <%= link_to challenges_path, class: "nav-link" do %>
        <% if current_page?(challenges_path) %>
          <i class="fas fa-tasks active"></i>
        <% else %>
          <i class="fas fa-tasks" ></i>
          <% end %>
        <% end %>
      </li>

       <li class="nav-item">
        <%= link_to new_challenge_path, class: "nav-link" do %>
          <% if current_page?(new_challenge_path) %>
            <i class="fas fa-camera active"></i></i>
        <% else %>
            <i class="fas fa-camera" ></i>
          <% end %>
        <% end %>
      </li>

      <li class="nav-item">
        <%= link_to users_path, class: "nav-link" do %>
          <% if current_page?(users_path)%>
            <i class="fas fa-sort-amount-up active"></i></i>
          <% else %>
            <i class="fas fa-sort-amount-up " ></i>
          <% end %>
        <% end %>
      </li>

      <li class="nav-avatar">
        <%= link_to user_path(current_user), class: "nav-link" do %>
          <% if current_page?(user_path(current_user)) %>
            <i class="fas fa-user active"></i></i>
            <% else %>
            <i class="fas fa-user " ></i>
          <% end %>
        <% end %>
      </li>

    <% else %>
      <li class="nav-item">
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      </li>
    <% end %>
  </ul>
</div>

app/views/users/index.html.erb
<div class="challenges">
  <h4 class="text-center">Top Challengers</h4>
</div>

 <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
<!-- selectionner user by score
afficher les 3 Highests scores
user_score.sort
@user.first(3) -->
    <% @top_users.each_with_index do |user, index| %>
      <div class="carousel-item <%= index == 0 ? 'active' : '' %>">
        <div class="card-user">
          <div class="card-user-infos">
            <div class="text-center">
             <%= cl_image_tag user.photo, class:"d-block"%>
            </div>
            <h1><%= user.first_name %></h1>
            <p><%= user.score %> pts</p>
            <div class="items text-center">
              <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="challenges">
  <h4 class="text-center"> Challengers </h2>
</div>
<div class="cards-users-list">
    <% @last_users.each_with_index do |user, index| %>
      <%= link_to user_path(user) do %>
        <div class="card-users">
          <%= cl_image_tag user.photo %>
          <div class="card-user-infos">
            <h2><%= user.first_name %></h2>
          </div>
          <div class="user_score"><%= user.score %> pts</div>
        </div>
      <% end %>
    <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="profile">
    <div class="card-profile">
      <%= cl_image_tag(@user.photo, :size => '100x100', class: 'rounded-circle') %>
      <h2 class="name-profile"><%= @user.first_name %> <%= @user.last_name %></h2>
      <p class="description-profile"><%= @user.description %></p>
    </div>
  </div>

  <div class='gauge-container'>
    <div class="bg-gauge">
      <div class="gauge" style='<%= user_score_to_css_width(@user) %>;'></div>
      <div class="turtle" style='<%= user_score_to_css_position(@user) %>'></div>
    </div>
  </div>

  <div class="challenges-block">
    <div class="challenges">
      <h4 class="my-challenges">My challenges</h4>
    </div>
    <div class="cards-challenges-list">
      <% @user.challenges.each do |challenge| %>
        <div class="card-challenge">
          <%= cl_image_tag challenge.photo, height: 100, width: 150, crop: :fill %>
          <div class="card-challenge-infos-16">
            <h6><%= challenge.title %></h6>
            <p><%= challenge.place %></p>
            <p><%= challenge.format_date %></p>
            <%= link_to "More details", challenge_path(challenge), class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="participations-block">
    <div class="participations">
      <h4 class="my-participations text-center">My participations</h4>
    </div>
    <div class="cards-challenges-list">
      <% @user.participations.each do |participation| %>
        <div class="card-challenge">
          <%= cl_image_tag participation.challenge.photo, height: 100, width: 150, crop: :fill %>
          <div class="card-challenge-infos-16">
            <h6><%= participation.challenge.title %></h6>
            <p><%= participation.challenge.place %></p>
            <p><%= participation.challenge.format_date %></p>
            <%= link_to "More details", challenge_path(participation.challenge), class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>